// Standard 66 Bible books — id matches the wldeh/bible-api book slug,
// de/en are display names, chapters is the total chapter count.
const bibleBooks = [
  {id:"genesis", de:"1. Mose (Genesis)", en:"Genesis", chapters:50},
  {id:"exodus", de:"2. Mose (Exodus)", en:"Exodus", chapters:40},
  {id:"leviticus", de:"3. Mose (Levitikus)", en:"Leviticus", chapters:27},
  {id:"numbers", de:"4. Mose (Numeri)", en:"Numbers", chapters:36},
  {id:"deuteronomy", de:"5. Mose (Deuteronomium)", en:"Deuteronomy", chapters:34},
  {id:"joshua", de:"Josua", en:"Joshua", chapters:24},
  {id:"judges", de:"Richter", en:"Judges", chapters:21},
  {id:"ruth", de:"Rut", en:"Ruth", chapters:4},
  {id:"1samuel", de:"1. Samuel", en:"1 Samuel", chapters:31},
  {id:"2samuel", de:"2. Samuel", en:"2 Samuel", chapters:24},
  {id:"1kings", de:"1. Könige", en:"1 Kings", chapters:22},
  {id:"2kings", de:"2. Könige", en:"2 Kings", chapters:25},
  {id:"1chronicles", de:"1. Chronik", en:"1 Chronicles", chapters:29},
  {id:"2chronicles", de:"2. Chronik", en:"2 Chronicles", chapters:36},
  {id:"ezra", de:"Esra", en:"Ezra", chapters:10},
  {id:"nehemiah", de:"Nehemia", en:"Nehemiah", chapters:13},
  {id:"esther", de:"Ester", en:"Esther", chapters:10},
  {id:"job", de:"Hiob", en:"Job", chapters:42},
  {id:"psalms", de:"Psalm", en:"Psalms", chapters:150},
  {id:"proverbs", de:"Sprüche", en:"Proverbs", chapters:31},
  {id:"ecclesiastes", de:"Prediger", en:"Ecclesiastes", chapters:12},
  {id:"songofsolomon", de:"Hohelied", en:"Song of Solomon", chapters:8},
  {id:"isaiah", de:"Jesaja", en:"Isaiah", chapters:66},
  {id:"jeremiah", de:"Jeremia", en:"Jeremiah", chapters:52},
  {id:"lamentations", de:"Klagelieder", en:"Lamentations", chapters:5},
  {id:"ezekiel", de:"Hesekiel", en:"Ezekiel", chapters:48},
  {id:"daniel", de:"Daniel", en:"Daniel", chapters:12},
  {id:"hosea", de:"Hosea", en:"Hosea", chapters:14},
  {id:"joel", de:"Joel", en:"Joel", chapters:3},
  {id:"amos", de:"Amos", en:"Amos", chapters:9},
  {id:"obadiah", de:"Obadja", en:"Obadiah", chapters:1},
  {id:"jonah", de:"Jona", en:"Jonah", chapters:4},
  {id:"micah", de:"Micha", en:"Micah", chapters:7},
  {id:"nahum", de:"Nahum", en:"Nahum", chapters:3},
  {id:"habakkuk", de:"Habakuk", en:"Habakkuk", chapters:3},
  {id:"zephaniah", de:"Zephanja", en:"Zephaniah", chapters:3},
  {id:"haggai", de:"Haggai", en:"Haggai", chapters:2},
  {id:"zechariah", de:"Sacharja", en:"Zechariah", chapters:14},
  {id:"malachi", de:"Maleachi", en:"Malachi", chapters:4},
  {id:"matthew", de:"Matthäus", en:"Matthew", chapters:28},
  {id:"mark", de:"Markus", en:"Mark", chapters:16},
  {id:"luke", de:"Lukas", en:"Luke", chapters:24},
  {id:"john", de:"Johannes", en:"John", chapters:21},
  {id:"acts", de:"Apostelgeschichte", en:"Acts", chapters:28},
  {id:"romans", de:"Römer", en:"Romans", chapters:16},
  {id:"1corinthians", de:"1. Korinther", en:"1 Corinthians", chapters:16},
  {id:"2corinthians", de:"2. Korinther", en:"2 Corinthians", chapters:13},
  {id:"galatians", de:"Galater", en:"Galatians", chapters:6},
  {id:"ephesians", de:"Epheser", en:"Ephesians", chapters:6},
  {id:"philippians", de:"Philipper", en:"Philippians", chapters:4},
  {id:"colossians", de:"Kolosser", en:"Colossians", chapters:4},
  {id:"1thessalonians", de:"1. Thessalonicher", en:"1 Thessalonians", chapters:5},
  {id:"2thessalonians", de:"2. Thessalonicher", en:"2 Thessalonians", chapters:3},
  {id:"1timothy", de:"1. Timotheus", en:"1 Timothy", chapters:6},
  {id:"2timothy", de:"2. Timotheus", en:"2 Timothy", chapters:4},
  {id:"titus", de:"Titus", en:"Titus", chapters:3},
  {id:"philemon", de:"Philemon", en:"Philemon", chapters:1},
  {id:"hebrews", de:"Hebräer", en:"Hebrews", chapters:13},
  {id:"james", de:"Jakobus", en:"James", chapters:5},
  {id:"1peter", de:"1. Petrus", en:"1 Peter", chapters:5},
  {id:"2peter", de:"2. Petrus", en:"2 Peter", chapters:3},
  {id:"1john", de:"1. Johannes", en:"1 John", chapters:5},
  {id:"2john", de:"2. Johannes", en:"2 John", chapters:1},
  {id:"3john", de:"3. Johannes", en:"3 John", chapters:1},
  {id:"jude", de:"Judas", en:"Jude", chapters:1},
  {id:"revelation", de:"Offenbarung", en:"Revelation", chapters:22}
];
